//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallManagement.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CallManagement.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are yoy sure you want to exit?.
        /// </summary>
        internal static string ApplicationClosingConfirmationText {
            get {
                return ResourceManager.GetString("ApplicationClosingConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application?.
        /// </summary>
        internal static string ApplicationClosingConfirmationTitle {
            get {
                return ResourceManager.GetString("ApplicationClosingConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbound: .
        /// </summary>
        internal static string barStatusItemInbound {
            get {
                return ResourceManager.GetString("barStatusItemInbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound:.
        /// </summary>
        internal static string barStatusItemOutbound {
            get {
                return ResourceManager.GetString("barStatusItemOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total calls: .
        /// </summary>
        internal static string barStatusItemTotalCalls {
            get {
                return ResourceManager.GetString("barStatusItemTotalCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this entry?.
        /// </summary>
        internal static string deleteEntryConfirmationText {
            get {
                return ResourceManager.GetString("deleteEntryConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry.
        /// </summary>
        internal static string deleteEntryConfirmationTitle {
            get {
                return ResourceManager.GetString("deleteEntryConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Call.
        /// </summary>
        internal static string editFormHeaderCreateCall {
            get {
                return ResourceManager.GetString("editFormHeaderCreateCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Call.
        /// </summary>
        internal static string editFormHeaderEditCall {
            get {
                return ResourceManager.GetString("editFormHeaderEditCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English already selected!.
        /// </summary>
        internal static string EnglishLanguageCaption {
            get {
                return ResourceManager.GetString("EnglishLanguageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek selected. Need to restart application to apply new settings.
        /// </summary>
        internal static string GreekLanguageCaption {
            get {
                return ResourceManager.GetString("GreekLanguageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        internal static string languageChangeRestartAppException {
            get {
                return ResourceManager.GetString("languageChangeRestartAppException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application?.
        /// </summary>
        internal static string languageChangeRestartAppText {
            get {
                return ResourceManager.GetString("languageChangeRestartAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string languageChangeRestartAppTitle {
            get {
                return ResourceManager.GetString("languageChangeRestartAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore Default Layout? Your current layout will be deleted!.
        /// </summary>
        internal static string resetLayoutText {
            get {
                return ResourceManager.GetString("resetLayoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Default Layout.
        /// </summary>
        internal static string resetLayoutTitle {
            get {
                return ResourceManager.GetString("resetLayoutTitle", resourceCulture);
            }
        }
    }
}
